# -*- coding: utf-8 -*-
"""roi_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaZYnm2ZcSJcD4duTMJ5uZMmUYLdDhgH
"""

def roi_calculator(cost_large, cost_small, acc_large, acc_small):

    savings_pct = ((cost_large - cost_small) / cost_large) * 100
    accuracy_loss_pct = (acc_large - acc_small) * 100

    if accuracy_loss_pct <= 0:
        return float("inf")
    return savings_pct / accuracy_loss_pct

if __name__ == "__main__":
    cost_70b = 0.0004699
    cost_8b = 0.0000714
    acc_70b = 0.95
    acc_8b = 0.90

    roi = roi_calculator(cost_70b, cost_8b, acc_70b, acc_8b)

    print("=== ROI Calculator ===")
    print(f"Cost (70B): ${cost_70b:.6f}")
    print(f"Cost (8B):  ${cost_8b:.6f}")
    print(f"Accuracy (70B): {acc_70b*100:.1f}%")
    print(f"Accuracy (8B):  {acc_8b*100:.1f}%")
    print(f"ROI: {roi:.2f}x (cost savings per unit accuracy loss)")